---
abstract: 'Include rss feeds on your page.'
author:
  - 'Marcus Ramberg <mramberg@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoMojo-Formatter-RSS
no_index:
  directory:
    - inc
    - t
requires:
  LWP::Simple: 0
  MojoMojo: 0
  URI::Fetch: 0
  XML::Feed: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
